# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "Dev", "DevOps", "Pipeline-Test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Syntax_check:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: Checkout from current branch
  #         uses: actions/checkout@v3

  #       - name: Lint Code Base
  #         uses: github/super-linter@v4
  #         env:
  #           VALIDATE_ALL_CODEBASE: false
  #           DEFAULT_BRANCH: "master"
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          


  Frontend_build:
    #needs: [Syntax_check]
    runs-on: ubuntu-latest
 
    steps:
        - name: Checkout from current branch
          uses: actions/checkout@v3
          
        - name: Build Front
          run: cd front && npm install && npm run build
        

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/highschool:${{ github.sha }}

        - name: Login to GHCR
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GHCR }} 
        
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          
        - name: Push to GHCR
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/highschool:latest
