# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "Dev", "DevOps", "Pipeline-Test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Syntax_check:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: Checkout from current branch
  #         uses: actions/checkout@v3

  #       - name: Lint Code Base
  #         uses: github/super-linter@v4
  #         env:
  #           VALIDATE_ALL_CODEBASE: false
  #           DEFAULT_BRANCH: "master"
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          


  Frontend_build:
    #needs: [Syntax_check]
    runs-on: ubuntu-latest
 
    steps:
        - name: Checkout from current branch
          uses: actions/checkout@v3
        
        - name: Build Docker container
          run: export $CR_PAT && ./devops/build.sh


        - name: Build Front
          run: cd front && npm install && npm run build
        

        
